USE dogs_db;

insert into dogs (age, name, reside_state) values (2, 'Zandra', 'TX');
insert into dogs (age, name, reside_state) values (3, 'Josey', 'NC');
insert into dogs (age, name, reside_state) values (9, 'Nikki', 'CA');
insert into dogs (age, name, reside_state) values (5, 'Freddi', 'FL');
insert into dogs (age, name, reside_state) values (11, 'Gino', 'WA');
insert into dogs (age, name, reside_state) values (15, 'Tess', 'TX');
insert into dogs (age, name, reside_state) values (2, 'Davidde', 'CA');
insert into dogs (age, name, reside_state) values (13, 'Gill', 'MO');
insert into dogs (age, name, reside_state) values (1, 'Eliza', 'TX');
insert into dogs (age, name, reside_state) values (7, 'Cindelyn', 'VA');
insert into dogs (age, name, reside_state) values (8, 'Alia', 'AZ');
insert into dogs (age, name, reside_state) values (4, 'Michail', 'WA');
insert into dogs (age, name, reside_state) values (6, 'Leonie', 'MS');
insert into dogs (age, name, reside_state) values (14, 'Garreth', 'AZ');
insert into dogs (age, name, reside_state) values (14, 'Gawen', 'PA');
insert into dogs (age, name, reside_state) values (7, 'Wilhelmina', 'GA');
insert into dogs (age, name, reside_state) values (5, 'Lorraine', 'AL');
insert into dogs (age, name, reside_state) values (8, 'Anson', 'TX');